### ISSUE TITLE
unhandled Prompt when patching  dbConfig_a.php.patch

### ISSUE THREAD

**Issue by rstormsf** [Dhar/ansible-suitecrm#4]
```
- name: Patch installation file
  shell: patch < dbConfig_a.php.patch
  args:
    chdir: "{{ suitecrm_install_dir }}/suitecrm-{{ suitecrm_version }}-max/install"
```

what happens is that it asks for user input:

```
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
```
